#!/bin/sh

cd ~

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

feh --bg-fill ~/.xmonad/root.png     # Set the wallpaper

# X11 settings
numlockx on                           # Turn on Num Lock
xmodmap ~/.Xmodmap
xset r rate 175 35 -b                 # Faster key repeat, no beep
xrdb ~/.Xresources                    # Overall X appearance and behavior
xsetroot -cursor_name left_ptr        # Don't want that ugly X cursor

# Start some daemons
xfce4-power-manager
gpgconf --launch gpg-agent

xscreensaver -no-splash & # Screensaver
trayer --edge bottom --align right --height 24 --SetPartialStrut true \
    --transparent true --alpha 32 --tint 0x002b36 --monitor primary &
volumeicon &              # Volume applet
compton -b                # Start the compositing manager
xmonad                    # Start the window manager
