#!/bin/sh

if ! dropbox running
then
    STATUS="`dropbox status`"
    SECONDS=`date +%s`
    TOGGLE=`expr $SECONDS % 2`

    if [ "$STATUS" = "Idle" -o $TOGGLE -eq 0 ]
    then
        echo '^i(.xmonad/icons/dropbox_idle.xbm) |'
    else
        echo '^i(.xmonad/icons/dropbox_busy.xbm) |'
    fi
fi
