#!/bin/sh

RED="\\#dc322f"

AMIXER=`amixer get 'Master' | awk '{if (NR == 5) print}'` 
MUTED=`echo "$AMIXER" | awk '{print $6}'`
VOLUME=`echo "$AMIXER" | awk '{print $4}' | tr -d '[%]'`

if [ "$MUTED" = "[off]" ]
then
    echo "^i(.xmonad/icons/spkr_mute.xbm) ^fg($RED)MUTE^fg()"
else
    printf "^i(.xmonad/icons/spkr_play.xbm) %3d%%" "$VOLUME"
fi
