#!/bin/sh

cd ~

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

feh --no-fehbg --bg-fill ~/.dotfiles/wm/root.png # Set the wallpaper

# X11 settings...
numlockx on			# Turn on Num Lock
xmodmap ~/.Xmodmap		# Key mappings
xset r rate 175 35 -b		# Faster key repeat, no beep
xrdb ~/.Xresources		# Overall X appearance and behavior
xsetroot -cursor_name left_ptr	# Don't want that ugly X cursor

# Start some daemons...
xfce4-power-manager
gpgconf --launch gpg-agent
xscreensaver -no-splash &
volumeicon &
compton -b

# And finally, the window manager. If it is killed due to SIGHUP, it will be
# restarted.
while true; do
	dwm
	if [ $? -ne 129 ]; then
		break
	fi
done
