#!/bin/sh

cd ~

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

feh --no-fehbg --bg-fill ~/.dotfiles/wm/root.png # Set the wallpaper

# X11 settings...
numlockx on			# Turn on Num Lock
xmodmap ~/.Xmodmap		# Key mappings
synclient VertScrollDelta=-114 HorizScrollDelta=-114 # Natural scrolling
xset r rate 150 50 -b		# Faster key repeat, no beep
xrdb ~/.Xresources		# Overall X appearance and behavior
xsetroot -cursor_name left_ptr	# Don't want that ugly X cursor

# Start some daemons...
xfce4-power-manager
gpgconf --launch gpg-agent
xscreensaver -no-splash &
redshift-gtk &
supavolumed &
statusbar &
compton &

# And finally, start the window manager.
while true; do
	dwm
	# If the window manager is killed due to SIGHUP, it will be restarted.
	# (Poor man's restart.)
	if [ $? -ne 129 ]; then
		break
	fi
done

# Kill previously started daemons.
kill $(jobs -p)
