#!/bin/sh

cd ~

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

feh --no-fehbg --bg-fill ~/.dotfiles/wm/root.png # Set the wallpaper

# X11 settings...
numlockx on			# Turn on Num Lock
synclient VertScrollDelta=-114 HorizScrollDelta=-114 # Natural scrolling
xrdb ~/.Xresources		# Overall X appearance and behavior
xsetroot -cursor_name left_ptr	# Don't want that ugly X cursor

# Start some daemons...
inputconfd --keyboard="xmodmap ~/.Xmodmap; xset r rate 150 50 -b" &
if [ -r ~/.gnupg/gpg-agent.conf ]; then
	gpgconf --launch gpg-agent
fi
if [ -r ~/.config/redshift.conf ]; then
	redshift-gtk &
fi
xfce4-power-manager --no-daemon &
xscreensaver -no-splash &
supavolumed &
verbar --wordy &
compton &

# And finally, start the window manager.
while true; do
	dwm
	# If the window manager is killed due to SIGHUP, it will be restarted.
	# (Poor man's restart.)
	if [ $? -ne 129 ]; then
		break
	fi
done

# Kill previously started daemons.
kill $(jobs -p)
