#!/bin/sh

hsetroot -fill ~/.xmonad/root.png       # Set the wallpaper

numlockx on                             # Turn on Num Lock
xmodmap -e 'clear lock'                 # Clear Caps Lock
xmodmap -e 'keycode 0x42 = Escape'      # Map Caps Lock to Esc
xmodmap -e 'keycode 0x09 = Caps_Lock'   # Map Esc to Caps Lock
xset r rate 175 25                      # Faster key repeat

xscreensaver -no-splash &               # Start the screensaver
xcompmgr &                              # Start the compositing manager
xmonad                                  # Start the window manager
