#!/usr/bin/env perl

use strict;
use warnings;

sub spawn_new_terminal
{
    my ($self) = @_;

    my $exe = readlink(sprintf("/proc/%d/exe", $$));
    my $pwd = readlink(sprintf("/proc/%d/cwd", $self->{child_pid}));

    my $pid = fork();
    if (defined $pid && $pid == 0) {
        exec("$exe", "-cd", "$pwd");
    }
}

sub on_child_start
{
    my ($self, $pid) = @_;
    $self->{child_pid} = $pid;

    ()
}

sub on_user_command
{
    my ($self, $cmd) = @_;
    if ($cmd eq "spawn-new-terminal") {
        spawn_new_terminal($self);
    }

    ()
}
