#!/bin/sh

cd ~

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

feh --no-fehbg --bg-fill ~/.config/wallpaper.png

# X11 settings...
numlockx on			# Turn on Num Lock
xrdb ~/.Xresources		# Overall X appearance and behavior
if [ -e ~/.Xresources.local ]; then
	xrdb -merge ~/.Xresources.local
fi
xsetroot -cursor_name left_ptr	# Don't want that ugly X cursor

# Touchpad settings...
for touchpad in $(xinput --list | sed -rn 's/.*touchpad.*id=([0-9]+).*/\1/Ip'); do
	xinput --set-prop "${touchpad}" "libinput Disable While Typing Enabled" 0
	xinput --set-prop "${touchpad}" "libinput Natural Scrolling Enabled" 1
	xinput --set-prop "${touchpad}" "libinput Tapping Enabled" 1
done

# Terminal settings...
dconf load /org/gnome/terminal/ < ~/.dotfiles/term/gnome-terminal.dconf

# Start some daemons...
inputconfd --keyboard="xmodmap ~/.Xmodmap; xset r rate 150 50 -b" &
if [ -r ~/.gnupg/gpg-agent.conf ]; then
	gpgconf --launch gpg-agent
fi
if [ -r ~/.config/redshift.conf ]; then
	redshift-gtk &
fi
xfce4-power-manager --no-daemon &
xscreensaver -no-splash &
supavolumed --step 2 &
dpi="$(xrdb -query -all | awk '$1 == "Xft.dpi:" { print $2 }')"
if [ ! -e "$HOME/.dotfiles/desktop/icons/$dpi" ]; then
	dpi=96
fi
verbar --icons "$HOME/.dotfiles/desktop/icons/$dpi" --wordy &
unset dpi
compton &

# And finally, start the window manager.
while true; do
	dwm
	# If the window manager is killed due to SIGHUP, it will be restarted.
	# (Poor man's restart.)
	if [ $? -ne 129 ]; then
		break
	fi
done

# Kill previously started daemons.
kill $(jobs -p)
