#!/bin/sh

set -e

if [ -e /tmp/.wifi_dropdown ]
then
    kill "$(cat /tmp/.wifi_dropdown)"
    rm /tmp/.wifi_dropdown
    rm /tmp/.wifi_conky
else
    cat > /tmp/.wifi_conky << EOF
background no
out_to_console yes
out_to_x no
update_interval 1.0

TEXT
\${wireless_essid $1}
EOF
    conky -c /tmp/.wifi_conky | dzen2 $(~/.xmonad/dzen_flags) -x 70% -y 14 -w 15% -ta l -e "button1=exit" &
    echo $! > /tmp/.wifi_dropdown
fi
